services:
  rabbit:
    image: rabbitmq:3-management-alpine
    hostname: rabbitmq
    container_name: rabbit
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq_data:/var/lib/rabbit/
      - rabbitmq_log:/var/log/rabbit/
    restart: always
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "5672" ]
      interval: 5s
      timeout: 15s
      retries: 3

  app-drones:
    build: ./app-drones
    ports:
      - 6000:5000
    command: gunicorn wsgi:app -b 0.0.0.0:5000
    environment:
      - RABBIT_HOST=${RABBIT_HOST}
      - RABBIT_PORT=${RABBIT_PORT}
      - RABBIT_USER=${RABBIT_USER}
      - RABBIT_PASSWORD=${RABBIT_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - GCP_CREDENTIALS_PROJECT_ID=${GCP_CREDENTIALS_PROJECT_ID}
      - GCP_CREDENTIALS_PRIVATE_KEY_ID=${GCP_CREDENTIALS_PRIVATE_KEY_ID}
      - GCP_CREDENTIALS_PRIVATE_KEY=${GCP_CREDENTIALS_PRIVATE_KEY}
      - GCP_CREDENTIALS_CLIENT_EMAIL=${GCP_CREDENTIALS_CLIENT_EMAIL}
      - GCP_CREDENTIALS_CLIENT_ID=${GCP_CREDENTIALS_CLIENT_ID}
      - GCP_CREDENTIALS_CLIENT_X509_CERT_URL=${GCP_CREDENTIALS_CLIENT_X509_CERT_URL}
    volumes:
      - /home/nfsshare:/nfsshare
    restart: always

  app-drones-worker:
    build: ./app-drones-worker
    command: python app.py
    environment:
      - RABBIT_HOST=${RABBIT_HOST}
      - RABBIT_PORT=${RABBIT_PORT}
      - RABBIT_USER=${RABBIT_USER}
      - RABBIT_PASSWORD=${RABBIT_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - GCP_CREDENTIALS_PROJECT_ID=${GCP_CREDENTIALS_PROJECT_ID}
      - GCP_CREDENTIALS_PRIVATE_KEY_ID=${GCP_CREDENTIALS_PRIVATE_KEY_ID}
      - GCP_CREDENTIALS_PRIVATE_KEY=${GCP_CREDENTIALS_PRIVATE_KEY}
      - GCP_CREDENTIALS_CLIENT_EMAIL=${GCP_CREDENTIALS_CLIENT_EMAIL}
      - GCP_CREDENTIALS_CLIENT_ID=${GCP_CREDENTIALS_CLIENT_ID}
      - GCP_CREDENTIALS_CLIENT_X509_CERT_URL=${GCP_CREDENTIALS_CLIENT_X509_CERT_URL}
    restart: always 
    volumes:
      - /home/nfsshare:/nfsshare


volumes:
  rabbitmq_data:
  rabbitmq_log:
  postgres_data:
  app-drones:
  app-drones-worker:

