version: "3.7"
services:
  rabbit:
    image: rabbitmq:3-management-alpine
    hostname: rabbitmq
    container_name: rabbit
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq_data:/var/lib/rabbit/
      - rabbitmq_log:/var/log/rabbit/
    restart: unless-stopped
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "5672" ]
      interval: 5s
      timeout: 15s
      retries: 3

  app-drones:
    build: ./app-drones
    ports:
      - 6000:5000
    command: flask run --host=0.0.0.0
    environment:
      - RABBIT_HOST=${RABBIT_HOST}
      - RABBIT_PORT=${RABBIT_PORT}
      - RABBIT_USER=${RABBIT_USER}
      - RABBIT_PASSWORD=${RABBIT_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - nfsshare:/nfsshare
    restart: on-failure

  app-drones-worker:
    build: ./app-drones-worker
    command: python app.py
    environment:
      - RABBIT_HOST=${RABBIT_HOST}
      - RABBIT_PORT=${RABBIT_PORT}
      - RABBIT_USER=${RABBIT_USER}
      - RABBIT_PASSWORD=${RABBIT_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    restart: on-failure
    volumes:
      - nfsshare:/nfsshare
  
  app-file-storage:
    image: itsthenetwork/nfs-server-alpine:12
    environment:
      SHARED_DIRECTORY: /nfsshare
    restart: unless-stopped
    volumes:
      - nfsshare:/nfsshare
    privileged: true
    ports:
      - "2049:2049"


volumes:
  nfsshare:
  rabbitmq_data:
  rabbitmq_log:
  postgres_data:
  app-drones:
    driver: nfs
    driver_opts:
      o: addr=${NFS_SERVER_IP},nolock,soft,rw
      device: :/nfsshare
