version: "3.2"
services:
  rabbit:
    image: rabbitmq:3-management-alpine
    hostname: rabbitmq
    container_name: rabbit
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/
      - rabbitmq_log:/var/log/rabbitmq/
    restart: unless-stopped
    networks:
      - rabbitmq_go_net
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "5672" ]
      interval: 5s
      timeout: 15s
      retries: 3  
  db:
    image: postgres
    environment:
      - POSTGRES_DB=vinyls
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - rabbitmq_go_net

  app-drones:
    build: ./app-drones
    ports:
      - 6000:5000
    command: flask run --host=0.0.0.0
    environment:
      - RABBIT_HOST=rabbit
      - POSTGRES_HOST=db
    depends_on:
      - db
      - rabbit
    networks:
      - rabbitmq_go_net
    volumes:
      - ./app-drones:/src
    restart: on-failure

  app-drones-worker:
    build: ./app-drones-worker
    command: python app.py
    environment:
      - RABBIT_HOST=rabbit
      - POSTGRES_HOST=db
    depends_on:
      - db
      - rabbit
    networks:
      - rabbitmq_go_net
    restart: on-failure
    


volumes:
  rabbitmq_data:
  rabbitmq_log:
  postgres_data:
  app-drones:

networks:
  rabbitmq_go_net:
    driver: bridge
    
